name: gstreamer_launch
description: A simple wrapper of gst for linux and windows.
version: 0.1.2-dev.1
homepage:
repository: https://github.com/Bardo91/gstreamer_launch

environment:
  sdk: ">=2.15.0-233.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  image: ^3.0.8  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: GstreamerLaunchPlugin
      windows:
        pluginClass: GstreamerLaunchPlugin
      android:
        package: com.bardo91.gstreamer_launch
        pluginClass: GstreamerLaunchPlugin

